package com.example.composegallery.ui.theme

import androidx.compose.ui.graphics.Color

val TealFollow = Color(0xFFB2DFDB)
val RedFollow = Color(0xFFFF6E6E)

val primaryLight = Color(0xFF3B6663)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFB2DFDB)
val onPrimaryContainerLight = Color(0xFF396461)
val secondaryLight = Color(0xFFAC3136)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFF6E6E)
val onSecondaryContainerLight = Color(0xFF6F0011)
val tertiaryLight = Color(0xFF635979)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD1C4E9)
val onTertiaryContainerLight = Color(0xFF5A506F)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF9F9F8)
val onBackgroundLight = Color(0xFF1A1C1C)
val surfaceLight = Color(0xFFF9F9F8)
val onSurfaceLight = Color(0xFF1A1C1C)
val surfaceVariantLight = Color(0xFFDCE4E2)
val onSurfaceVariantLight = Color(0xFF9E9E9E)
val outlineLight = Color(0xFF717977)
val inverseSurfaceLight = Color(0xFF2F3130)
val inverseOnSurfaceLight = Color(0xFFF0F1F0)

val primaryDark = Color(0xFFCEFCF7)
val onPrimaryDark = Color(0xFF053734)
val primaryContainerDark = Color(0xFFB2DFDB)
val onPrimaryContainerDark = Color(0xFF396461)
val secondaryDark = Color(0xFFFFB3B0)
val onSecondaryDark = Color(0xFF68000F)
val secondaryContainerDark = Color(0xFFFF6E6E)
val onSecondaryContainerDark = Color(0xFF6F0011)
val tertiaryDark = Color(0xFFEDE1FF)
val onTertiaryDark = Color(0xFF342C49)
val tertiaryContainerDark = Color(0xFFD1C4E9)
val onTertiaryContainerDark = Color(0xFF5A506F)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF111413)
val onBackgroundDark = Color(0xFFE2E3E1)
val surfaceDark = Color(0xFF111413)
val onSurfaceDark = Color(0xFFE2E3E1)
val surfaceVariantDark = Color(0xFF404847)
val onSurfaceVariantDark = Color(0xFFC0C8C7)
val outlineDark = Color(0xFF8A9291)
val inverseSurfaceDark = Color(0xFFE2E3E1)
val inverseOnSurfaceDark = Color(0xFF2F3130)